config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    post :confirm, on: :collection
    resources :comments
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  root 'top#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:edit, :update, :destroy]

  def create
    @comment = current_user.comments.build(comment_params)
    @topic = @comment.topic
    respond_to do |format|
      if @comment.save
        format.html {redirect_to topics_path, notice: 'コメントを投稿しました。'}
        format.js {render :index}
      else
        format.html {redirect_to topics_path, alert: "コメント文を入力して下さい。"}
      end
    end
  end

  def edit
    # respond_to do |format|
    #   format.html {redirect_to edit_topic_comment_path}
    #   format.js {render :edit, topic: @topic}
    # end
  end

  def update
    @comment.update(comment_params)
    if @comment.save
      redirect_to topics_path
    else
      render 'edit'
    end
  end

  def destroy
    respond_to do |format|
      @comment.destroy
      format.html {redirect_to topics_path, notice: 'コメントを削除しました。'}
      format.js {render :index}
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:topic_id, :content)
    end

    def set_comment
      @comment = Comment.find(params[:id])
      @topic = @comment.topic
      # 成りすましチェック
      if @comment.user_id != current_user.id
        redirect_to root_path, alert: "通報しました。"
        return
      end
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(comment, url: topic_comments_path(topic), remote: true ) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation" >
      <h4><%= comment.errors.count %>件のエラーがあります。</h4>
      <ul>
        <% comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="comment_form_box">
    <div class="field" id="comment_form_area">
      <%= f.hidden_field :topic_id %>
      <%= f.text_field :content, placeholder: "コメントを入力", class: "form-control", id: "comment_form" %>
    </div>
    <div class="actions">
      <%= f.submit "投稿", class: 'btn btn-primary btn-block', id: 'comment_submit_btn' %>
    </div>
  </div>
<% end %>

app/views/comments/_index.html.erb
<% comments.each do |comment| %>
  <% unless comment.id.nil? %>
    <div class="comment_area">
      <div class="comment_user_area">
        <div class = "comment_profile_image">
          <%= profile_img(comment.user) %>
        </div>
          <div class="comment_user_name">
            <p><%= comment.user.name %>さん</p>
          </div>
        <div class="pass_time">
          <p><%= time_ago_in_words(comment.updated_at) %>前</p>
        </div>
      </div>
      <div class="comment_content">
        <p><%= comment.content %></p>
      </div>
      <% if current_user.id == comment.user_id %>
        <div class="comment_edit_delete_icons">
          <%= link_to "", edit_topic_comment_path(topic, comment), class: "fa fa-pencil-square-o fa-lg" %>
          <%= link_to "", topic_comment_path(topic, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: {confirm: '本当に削除していいですか？'} %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/comments/edit.html.erb
<div class="container">
  <div class="row">
    <div class="wrapper col-md-5 col-md-offset-3 col-sm-10">
      <h4>コメントを編集</h4>

      <%= form_for(@comment, url: topic_comment_path) do |f| %>

        <%= f.error_messages! %>

        <%= f.text_area :content, :size => "20x3", class: 'form-control' %><br/>

        <%= f.submit "編集" %>

      <% end %>

      <%= link_to "トピック一覧へ戻る", topics_path %>

    </div>
  </div>
</div>

app/views/comments/index.js.erb
$("#comments_area_<%= @topic.id %>").html("<%= j(render 'comments/index', {comments: @topic.comments, topic: @topic}) %>")
$(':text').val('')