config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    post :confirm, on: :collection
    resources :comments
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  root 'top#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  default_scope -> {order(updated_at: :desc)}

  validates :content, presence: true

  belongs_to :user

  has_many :comments, dependent: :destroy

  mount_uploader :picture, PictureUploader

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:edit, :update, :destroy]

  def index
    @topics = Topic.all
    @topic = Topic.new
  end

  def new
    if params[:back]
      @topic = Topic.new(topic_params)
    else
      @topic = Topic.new
    end
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    if @topic.save
      redirect_to topics_path, notice: "新しいトピックを投稿しました！"
    else
      @topics = Topic.all
      @topic = Topic.new
      redirect_to topics_path, alert: "本文を入力して下さい。"
      # render 'new'
    end
  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      redirect_to topics_path, notice: "トピックを編集しました！"
    else
      render 'edit'
    end
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def destroy
    @topic.destroy
    redirect_to topics_path, notice: "トピックを削除しました！"
  end

# TBD confirmation routing.
  # def confirm
  #   @topic = Topic.new(topic_params)
  #   render :new if @topic.invalid?
  # end

  private

    def topic_params
      params.require(:topic).permit(:content, :picture)
    end

    def set_topic
      @topic = Topic.find(params[:id])
      # 成りすましチェック
      if @topic.user_id != current_user.id
        redirect_to root_path, alert: "通報しました。"
        return
      end
    end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_new.html.erb
<%= form_for(@topic) do |f| %>

  <%= f.error_messages! %>

  <div class="topic_create_user_form">
    <div class="topic_profile_image" >
      <%= profile_img(current_user) %>
    </div>
    <div class="topic_create_form">
      <%= f.text_area :content, placeholder: "今なにしてる？", class: 'form-control', id: "topic_form" %>
    </div>
  </div>
  <div class="topic_uploader_message">
    写真
  </div>
  <div class="topic_new_picture_img_area">
    <%= picture_img(@topic) if @topic.picture?%>
  </div>
  <%= f.file_field :picture %>
  <%= f.hidden_field :picture_cache %>
  <div class="topic_posting_btn_area">
    <%= f.submit "トピックを作成", class: 'btn btn-primary btn-block', id: 'topic_posting_btn' %>
  </div>
<% end %>

app/views/topics/confirm.html.erb
<h4>以下の内容で投稿して良いですか？</h4>

<%= form_for(@topic) do |f| %>
  <%= f.hidden_field :content %>
  <%= f.hidden_field :picture %>
  <%= @topic.content %>
  <%= picture_img(@topic) if @topic.picture?%>
  <%= f.submit "投稿", class: 'btn btn-primary btn-block' %>
<% end %>

<%= form_for(@topic, url: new_topic_path, method: 'get') do |f| %>
  <%= f.hidden_field :content %>
  <%= f.hidden_field :picture %>
  <%= f.submit "戻る", name: 'back', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/topics/edit.html.erb
<div class="container">
  <div class="row">
    <div class="wrapper col-md-5 col-md-offset-3 col-sm-10">
      <h4>トピックを編集</h4>

      <%= form_for(@topic, url: topic_path) do |f| %>

        <%= f.error_messages! %>
        <%= f.label :content %>
        <%= f.text_area :content, :size => "20x3", class: 'form-control' %><br/>

        <%= picture_img(@topic) if @topic.picture?%>
        <%= f.label :picture %>
        <%= f.file_field :picture %>
        <%= f.hidden_field :picture_cache %>
        <%= f.submit "投稿" %>

      <% end %>

      <%= link_to "トピック一覧へ戻る", topics_path %>

    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="container">
  <div class="row">
    <div class="wrapper col-lg-6 col-lg-offset-3 col-md-7 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-12">

      <% if alert != nil %>
      <div class="alert alert-danger" role="alert">
        <button type="button" data-dismiss="alert" class="close">&times;</button>
        <p><%= alert %></p>
      </div>
      <% elsif notice != nil %>
        <div class="alert alert-success" role="alert">
          <button type="button" data-dismiss="alert" class="close">&times;</button>
          <p><%= notice %></p>
        </div>
      <% end %>

      <div id="topic_create_area">
        <%= render partial: 'topics/new', locals: {topic: @topic} %>
      </div>

      <% @topics.each do |topic| %>
        <div class="topic_box">

          <div class="topic_user_area">

            <div class="topic_profile_image" >
              <%= profile_img(topic.user) %>
            </div>

            <div class="topic_action_area">
              <div class="topic_user_name"><%= topic.user.name %>さんが投稿しました。</div>
              <div class="topic_post_time"><%= topic.updated_at %></div>
            </div>

          </div>

          <div class="topic_content_area">
            <p><%= topic.content %></p>
          </div>

          <div class="topic_picture_area">
            <%= picture_img(topic) if topic.picture?%>
          </div>

          <% if current_user.id == topic.user_id %>
            <div class="btn_box">
              <div class="btn_area">
                <%= link_to "編集", edit_topic_path(topic.id), class: 'btn btn-primary btn-block', id: 'topic_btn' %>
                <%= link_to "削除", topic_path(topic.id), data: { confirm: "本当に削除して良いですか？" }, method: :delete, class: 'btn btn-primary btn-block', id: 'topic_btn' %>
              </div>
            </div>
          <% end %>

          <div id="comments_area_<%= topic.id %>">
            <%= render partial: 'comments/index', locals: {comments: topic.comments, topic: topic} %>
          </div>
          <%= render partial: 'comments/form', locals: {comment: topic.comments.build, topic: topic} %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/topics/new.html.erb
<div class="container">
  <div class="row">
    <div class="wrapper col-md-5 col-md-offset-3 col-sm-10">
      <h4>新規トピック作成</h4>

      <%= form_for(@topic) do |f| %>

        <%= f.error_messages! %>

        <%= f.label :content %>
        <%= f.text_area :content, :size => "20x3", class: 'form-control' %>

        <%= f.label :picture %>
        <%= picture_img(@topic) if @topic.picture?%>
        <%= f.file_field :picture %>
        <%= f.hidden_field :picture_cache %>

        <%= f.submit "投稿" %>
      <% end %>

      <%= link_to "トピック一覧へ戻る", topics_path %>

    </div>
  </div>
</div>