config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    post :confirm, on: :collection
    resources :comments
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  root 'top#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

  has_many :topics, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :followers, through: :reverse_relationships, source: :follower

  mount_uploader :avatar, AvatarUploader



  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end


  def self.create_unique_string
    SecureRandom.uuid
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
  # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @followed_users = @user.followed_users
    @followers = @user.followers
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>" >
  <% unless current_user.following?(user) %>
    <%= form_for(current_user.relationships.build(followed_id: user.id), remote: true) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォローする", class: "btn btn-primary", id: "user_follow_btn" %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.find_by(followed_id: user.id), html: {method: :delete}, remote: true) do |f| %>
    <%= f.submit "フォロー解除", class: "btn btn-primary", id: "user_unfollow_btn" %>
    <% end %>
  <% end %>
</div>

app/views/users/_followed_users.html.erb
<h4>フォロー数 ： <%= @followed_users.count %>人</h4>
<% @followed_users.each do |user| %>
  <% unless current_user.id == user.id %>
      <div class="user_index_area">
        <div class="user_index_profile_image" >
          <%= profile_img(user) %>
        </div>
        <div class="user_index_name">
          <%= link_to "#{user.name}", user_path(user)  %>
        </div>
        <div class="user_index_follow_form">
          <%= render 'follow_form', user: user %>
        </div>
      </div>
  <% end %>
<% end %>

app/views/users/_followers.html.erb
<h4>フォロワー数 ： <%= @followers.count %>人</h4>
<% @followers.each do |user| %>
  <% unless current_user.id == user.id  then %>
    <div class="user_index_area">
      <div class="user_index_profile_image" >
        <%= profile_img(user) %>
      </div>
      <div class="user_index_name">
        <%= link_to "#{user.name}", user_path(user)  %>
      </div>
      <div class="user_index_follow_form">
        <%= render 'follow_form', user: user %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="wrapper col-md-5 col-md-offset-3 col-sm-10">
      <h4>ユーザー一覧</h4>
      <% @users.each do |user| %>
        <% unless user == current_user %>
          <div class="user_index_area">
            <div class="user_index_profile_image" >
              <%= profile_img(user) %>
            </div>
            <div class="user_index_name">
              <%= link_to "#{user.name}", user_path(user)  %>
            </div>
            <div class="user_index_btn_box">
              <div class="user_index_message_button">
                <%= link_to "メッセージ", conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post', class: "btn btn-primary btn-block", id: "user_index_message_btn" %>
              </div>
              <div class="user_index_follow_form">
                <%= render partial: 'follow_form', locals: {user: user} %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="wrapper col-md-5 col-md-offset-3 col-sm-10">

          <div class="user_show_area">
            <div class="user_show_profile_image" >
              <%= profile_img(@user) %>
            </div>
            <div class="user_show_name">
              <%= @user.name %>
            </div>
            <div class="user_show_follow_form">
              <%= render 'follow_form', user: @user %>
            </div>
          </div>

          <div class="user_show_followed_users_area">
            <%= render partial: 'followed_users', locals: {user: @user, followed_users: @followed_users} %>
          </div>

          <div class="user_show_followers_area">
            <%= render partial: 'followers', locals: {user: @user, followers: @followers} %>
          </div>

    </div>
  </div>
</div>