config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    post :confirm, on: :collection
    resources :comments
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  root 'top#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Friendchain</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<% unless current_page?(root_path) %>
  <body <%= "class=body_login" %> >
<% else %>
  <body <%= "class=body_logoff" %>
<% end %>


  <header>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <!-- <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button> -->

          <!-- change logo belongs to login/logoff -->
          <% if user_signed_in? %>
            <div class="logo_container_login" >
            <%= link_to image_tag('logo_login.png'), topics_path %>
            </div>
          <% else %>
            <div class="logo_container_logoff" >
            <%= link_to image_tag('logo_logoff.png'), root_path %>
            </div>
          <% end %>

        </div>

        <% if user_signed_in? %>

          <div class="header_signed_in">

            <div class="header_user_edit">
              <%= link_to current_user.name, edit_user_registration_path, class: 'btn btn-primary btn-block', id: 'user_edit_btn' %>
            </div>
            <div class="header_topic_index">
              <%= link_to image_tag('friendchain_earth_icon.png'), topics_path %>
            </div>
            <div class="header_all_user">
              <%= link_to image_tag('friendchain_all_users_icon.png'), users_path %>
            </div>
            <% if new_message_arrival_count(current_user) == 0 %>
              <div class="header_message">
                <%= link_to image_tag('friendchain_message_none_icon.png'), conversations_path %>
              </div>
            <% else %>
              <div class="header_message">
                <%= link_to image_tag('friendchain_message_newarrival_icon.png'), conversations_path %>
              </div>
              <div class="header_message_new_arrival_count">
                <p><%= @count %></p>
              </div>
            <% end %>
            <div class="header_logoff">
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
            </div>

          </div>

        <% else %>
          <% if current_page?(root_path) %>
            <div class="login_form_box", id="login_form_box">

              <%= form_for(:user, url: session_path(:user), html: { class: "navbar-form navbar-right form-inline" }) do |f| %>
                <div class="form-group" id="login_form_email_box">
                  <%= f.label :メールアドレス %><br />
                  <%= f.text_field :email, class: "form-control", id: "login_form_email" %>
                </div>
                <div class="form-group" id="login_form_pwd_box">
                  <%= f.label :パスワード %><br />
                  <%= f.password_field :password, class: "form-control", id: "login_form_pwd"  %><br />
                  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
                    <%= link_to "パスワードを忘れた場合", new_password_path(resource_name) %><br />
                  <% end -%>
                </div>
                <div class="form-group" id="login_form_btn_box">
                  <%= f.submit "ログイン", class: 'btn btn-primary btn-block', id: 'login_btn'%><br />
                </div>
              <% end %>

            <% end %>

          </div>
        <% end %>
      </div><!-- /.container-fluid -->
    </nav>

  </header>


<%= yield %>

  <footer>
    <p>friendchain &copy; 2017</p>
  </footer>

</body>
</html>